# Generated by Django 6.0.7 on 2026-07-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
